logging:
  level:
    root: info
  file:
    path: logs
    name: ${logging.file.path}/${spring.application.name}.log
    max-size: 100MB
    max-history: 15
    total-size-cap: 5GB
spring:
  application:
    name: abdp
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
server:
  servlet:
    context-path: /abdp